### ISSUE TITLE
the normal generation throughout  reference

### ISSUE THREAD

**Issue by ltm920716** [deepseek-ai/DeepSeek-V3#24]
hi，
  I deploy the v3 model with vllm on 8*H200（tp=8），and the generation throughout is round 10 tokens/s，I thinks this is some slow，so could you give me a reference about the normal generation throughout，or some method to improve the throughout，thanks！

**Comment by GeeeekExplorer** [comment]
In fact, the demo is only used to show the model structure. It is mainly limited by CPU and you can observe that the kernel launching is very slow using torch profile. For faster speed you can try sglang or vllm.

**Comment by ltm920716** [comment]
> In fact, the demo is only used to show the model structure. It is mainly limited by CPU and you can observe that the kernel launching is very slow using torch profiler. For faster speed you can try sglang or vllm.

actually，I do deploy the model with vllm/vllm-openai:v0.6.6，so I want to know how to improve the throughout

**Comment by GeeeekExplorer** [comment]
I think cudagraph would be helpful if supported.

**Comment by mowentian** [comment]
Please refer to the work vllm DeepSeek-V3 Enhancements  https://github.com/vllm-project/vllm/issues/11539

**Comment by zhaotyer** [comment]
> hi， I deploy the v3 model with vllm on 8*H200（tp=8），and the generation throughout is round 10 tokens/s，I thinks this is some slow，so could you give me a reference about the normal generation throughout，or some method to improve the throughout，thanks！

Hi, can you send me your startup method?

**Comment by ltm920716** [comment]
> > hi， I deploy the v3 model with vllm on 8*H200（tp=8），and the generation throughout is round 10 tokens/s，I thinks this is some slow，so could you give me a reference about the normal generation throughout，or some method to improve the throughout，thanks！
> 
> Hi, can you send me your startup method?
hi，
my k8s yaml:
```
containers:
    - args:
        - '--model'
        - /data/model/deepseekv3
        - '--max-model-len'
        - '4096'
        - '--tensor-parallel-size'
        - '8'
        - '--served-model-name'
        - 'deepseek'
        - '--trust-remote-code'
      image: 172.28.35.101:10001/private_000000/vllm/vllm-openai:v0.6.6
```
